version: "3.9"

name: firefox
services:
  firefox:
    image: rshmyrev/firefox
    build: .
    environment:
      - DISPLAY=unix$DISPLAY # X11
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native # pulse
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # X11
      - $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse:ro # pulse
      - cache:/cache
      - config:/config
      - $HOME/Downloads:/downloads

volumes:
  cache:
  config:
